# Generated by Django 3.0.2 on 2020-01-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatinho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatinho',
            name='cor',
            field=models.CharField(choices=[('PRETO', 'Preto'), ('BRANCO', 'Branco'), ('PARDO', 'Pardo')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
